name: 📚 Documentation Issue
description: Report errors or suggest improvements in documentation
title: "[Docs]: "
labels: ["documentation"]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the Issue
      description: What's wrong or missing in the documentation?
    validations:
      required: true